language: elixir
elixir:
- 1.6
cache:
  directories:
    - _build
    - deps
deploy:
  provider: heroku
  app: optimalist
  api_key:
    secure: Gg90n1vSJcWbhjzjIpd6JZoX/XEpLYj8b52nAI4nWHLxUwvdHKyYsF/TlViNySlBWvDPtRbKA2/U0fuBlxGOw8UILnZqYi6xpLW5vOofkViufv3ydVJZOXrWVzqFX3TXWh6cy0//gFxGGcNyCxs64VAVNnBvGZ8nSbHjA5VtO5I=
